apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
        - name: demo-app-container
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          volumeMounts:
            - mountPath: /mnt/data
              name: efs-volume
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: demo-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-12345678 # Replace with your EFS file system ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pv
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeMode: Filesystem # Filesystem volume mode
