apiVersion: apps/v1
kind: Deployment
metadata:
  name: emptydir-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: busybox
          command: ["sh", "-c", "sleep 3600"]
          volumeMounts:
            - mountPath: /tmp/data
              name: temp-storage
      volumes:
        - name: temp-storage
          emptyDir: {}
