apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  namespace: demo
spec:
  serviceAccountName: demo
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    # startupProbe:
    #   exec:
    #     command:
    #       - /bin/my-script.sh
    #   initialDelaySeconds: 60
    #   timeoutSeconds: 10
    # livenessProbe:
    #   exec:
    #     command:
    #       - /bin/my-script.sh
    #   initialDelaySeconds: 60
    #   timeoutSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /
    #     port: 80
    #     scheme: HTTP
    #     initialDelaySeconds: 5
    #     periodSeconds: 10
    #     timeoutSeconds: 3
    #     successThreshold: 1
    #     failureThreshold: 3



