apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo
  namespace: demo
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["autoscaling"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources: ["*"]
  verbs: ["*"]

---
# Define a role binding to bind the role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: demo
    namespace: demo
roleRef:
  kind: Role
  name: demo
  apiGroup: rbac.authorization.k8s.io
