apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo
  namespace: demo
---
apiVersion: v1
kind: Secret
metadata:
  name: demo
  namespace: demo
  annotations:
    kubernetes.io/service-account.name: demo
type: kubernetes.io/service-account-token
