apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace: elearning
spec:
  containers:
    - name: mysql-client
      image: mysql:8.0
      command: ["sleep"]
      args: ["3600"]
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
  restartPolicy: Never
