apiVersion: batch/v1
kind: CronJob
metadata:
  name: example-cronjob
spec:
  schedule: "* * * * *"
  suspend: false
  jobTemplate:
    spec:
      parallelism: 2
      completions: 2
      backoffLimit: 4
      activeDeadlineSeconds: 100
      template:
        spec:
          containers:
            - name: example
              image: busybox
              command: ["echo", "Hello, Kubernetes!"]
          restartPolicy: OnFailure
      # ttlSecondsAfterFinished: 15
